language: objective-c
osx_image: xcode11.2
xcode_project: StringCalculator.xcodeproj
xcode_scheme: StringCalculator
xcode_sdk: iphonesimulator13.0
script: xcodebuild -project StringCalculator.xcodeproj -scheme StringCalculator -destination "platform=iOS Simulator,OS=13.2,name=iPhone 11 Pro" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test | xcpretty
